version: '3.7'
services:
  credit:
    image: docker.pkg.github.com/sylwiaxbiniek/zadaniejava/credit:1.0-SNAPSHOT
    command: java -jar /usr/share/credit/credit.jar
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
  customer:
    image: docker.pkg.github.com/sylwiaxbiniek/zadaniejava/customer:1.0-SNAPSHOT
    command: java -jar /usr/share/customer/customer.jar
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
  product:
    image: docker.pkg.github.com/sylwiaxbiniek/zadaniejava/product:1.0-SNAPSHOT
    command: java -jar /usr/share/product/product.jar
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zadaniejava
